name: backup-admin
run-name: Make backup of HYC results admin DB
on:
  workflow_dispatch:
  schedule:
      - cron: 12 6 * * *
jobs:
  create-admin-backup-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: scripts/admin/requirements.txt
      - name: Update admin DB backup
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          pip install -r scripts/admin/requirements.txt
          rm -f backups/admin/202{2,3}_*.csv
          make admin-backup
      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Admin DB backup
          title: Admin DB backup
          add-paths: backups/admin/
          branch: create-pull-request/admin-backup
